### ISSUE TITLE
请问一下构建的时候找不到godot属性应该怎么解决

### ISSUE THREAD

**Issue by ACGNnsj** [529124368/rust_websocket_demo#1]
![image](https://user-images.githubusercontent.com/22112141/210959216-74e72a3d-bb3b-43ec-9c38-28a15704b444.png)
= =对rust不太熟悉 这个我折腾一会儿实在解决不了

**Comment by 529124368** [comment]
@ACGNnsj 

哦哦，这个你需要参考下这里。需要搞下环境才可以
https://github.com/godot-rust/gdnative
